(() => {
'use strict';
const extra=document.createElement('link');extra.rel='stylesheet';extra.href='team.css';document.head.appendChild(extra);
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const SAVE='blob-quest-save:',AUTH='blob-quest-auth:',LAST='blob-quest-last-account';
const MAPS=[
{name:'暮色草原',sky:'#8a69cf',far:'#5e4ca4',ground:'#4b3a82',mobs:['綠葉史萊姆','藍帽史萊姆','紅角史萊姆']},
{name:'櫻霞山谷',sky:'#d877b2',far:'#9b4f91',ground:'#5d376c',mobs:['櫻花史萊姆','忍者史萊姆','狐面史萊姆']},
{name:'霜月雪原',sky:'#78b9d8',far:'#4c75a0',ground:'#40557c',mobs:['冰晶史萊姆','雪帽史萊姆','冰王史萊姆']},
{name:'幽影城堡',sky:'#55477f',far:'#30294f',ground:'#25213c',mobs:['幽靈史萊姆','黑騎史萊姆','深淵史萊姆']}];
const ROLES=[
{id:'swordsman',name:'劍士',icon:'⚔',unlock:1,color:'#ef5864',skill:'烈焰斬',desc:'高倍率斬擊',cd:5,mult:2.5,interval:950},
{id:'mage',name:'法師',icon:'✦',unlock:5,color:'#9a5dde',skill:'星爆術',desc:'爆發魔法傷害',cd:8,mult:3.4,interval:1200},
{id:'gunner',name:'槍手',icon:'▰',unlock:10,color:'#45a7e9',skill:'三連射',desc:'連續射擊三次',cd:6,mult:1.15,interval:720},
{id:'tank',name:'坦克',icon:'⬢',unlock:15,color:'#e6a04a',skill:'守護壁壘',desc:'減傷並反擊',cd:10,mult:1.25,interval:1450},
{id:'doctor',name:'醫生',icon:'✚',unlock:20,color:'#55c879',skill:'群體治療',desc:'回復隊伍生命',cd:12,mult:.38,interval:1350}];
const TYPE={weapon:['武器','🗡️'],helmet:['頭盔','🪖'],armor:['鎧甲','🛡️'],boots:['戰靴','🥾'],ring:['戒指','💍'],amulet:['項鍊','📿']},RN=['普通','優良','稀有','史詩','傳說','神話'],RM=[1,1.45,2.1,3.2,4.9,7.5];
const cv=$('#battleCanvas'),ctx=cv.getContext('2d');ctx.imageSmoothingEnabled=false;
let S=null,E=null,user='',pending=null,lastEnemy=0,frameAt=0,respawnAt=0,shieldUntil=0,attackIndex=0;
const lastAttack={},ready={},shots=[],sparks=[];
const fmt=n=>Math.floor(Number(n)||0).toLocaleString('en-US'),clamp=(v,a,b)=>Math.min(b,Math.max(a,v)),gstage=()=>S.mapIndex*10+S.stage;
function clean(v){return String(v||'').trim().replace(/[^a-zA-Z0-9_\-\u3400-\u9fff]/g,'').slice(0,20)}
function get(k){try{return localStorage.getItem(k)}catch{return null}}function set(k,v){try{localStorage.setItem(k,v);return true}catch{toast('瀏覽器阻止儲存');return false}}
function bytesHex(buf){return [...new Uint8Array(buf)].map(b=>b.toString(16).padStart(2,'0')).join('')}
async function hashPassword(password,salt){const text=`${salt}|${password}`;if(window.crypto&&crypto.subtle){return bytesHex(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text)))}let h=2166136261;for(let i=0;i<text.length;i++){h^=text.charCodeAt(i);h=Math.imul(h,16777619)}return (h>>>0).toString(16)}
function randomSalt(){if(window.crypto&&crypto.getRandomValues){const a=new Uint8Array(16);crypto.getRandomValues(a);return bytesHex(a)}return Math.random().toString(36).slice(2)+Date.now().toString(36)}
async function register(){const a=clean($('#accountInput').value),p=$('#passwordInput').value;if(!a)return authError('請輸入帳戶名稱');if(p.length<4)return authError('密碼至少需要 4 個字元');if(get(AUTH+a.toLowerCase()))return authError('帳戶已存在，請直接登入');const salt=randomSalt(),hash=await hashPassword(p,salt);set(AUTH+a.toLowerCase(),JSON.stringify({salt,hash}));await enter(a,true)}
async function login(){const a=clean($('#accountInput').value),p=$('#passwordInput').value;if(!a||!p)return authError('請輸入帳戶及密碼');const raw=get(AUTH+a.toLowerCase());if(!raw)return authError('找不到帳戶，請先建立帳戶');try{const rec=JSON.parse(raw),hash=await hashPassword(p,rec.salt);if(hash!==rec.hash)return authError('密碼不正確')}catch{return authError('帳戶資料損壞，請使用另一個帳戶')}await enter(a,false)}
function authError(t){$('#loginError').textContent=t}
function fresh(a){return{version:3,account:a,level:1,xp:0,xpToNext:100,gold:250,gems:30,mapIndex:0,stage:1,killsInStage:0,totalKills:0,dailyKills:0,auto:true,partyHp:null,enhancement:0,skillLevels:{swordsman:1,mage:1,gunner:1,tank:1,doctor:1},equipment:{weapon:null,helmet:null,armor:null,boots:null,ring:null,amulet:null},inventory:[],savedAt:Date.now()}}
function normalize(v,a){const f=fresh(a),o=Object.assign(f,v||{});o.skillLevels=Object.assign(f.skillLevels,v&&v.skillLevels||{});o.equipment=Object.assign(f.equipment,v&&v.equipment||{});o.inventory=Array.isArray(v&&v.inventory)?v.inventory.slice(0,60):[];o.mapIndex=clamp(+o.mapIndex||0,0,MAPS.length-1);o.stage=clamp(+o.stage||1,1,10);return o}
async function enter(a,newAccount){user=a;const raw=get(SAVE+a.toLowerCase());let data=null;if(raw){try{data=JSON.parse(raw)}catch{}}S=normalize(data,a);set(LAST,a);$('#loginScreen').classList.add('hidden');$('#gameScreen').classList.remove('hidden');if(raw&&Date.now()-S.savedAt>60000){const sec=Math.min(28800,(Date.now()-S.savedAt)/1000);pending={gold:Math.floor(sec*(1.8+gstage()*.42)),xp:Math.floor(sec*(.35+gstage()*.075))};$('#offlineReward').textContent=`🪙 ${fmt(pending.gold)}　⭐ ${fmt(pending.xp)} XP`;$('#offlineModal').classList.remove('hidden')}spawn(true);render();log(newAccount?'帳戶建立成功，冒險開始！':'登入成功，已載入存檔。');resize()}
function save(show=false){if(!S)return;S.savedAt=Date.now();if(set(SAVE+user.toLowerCase(),JSON.stringify(S))){$('#saveStatus').textContent='已儲存 '+new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});if(show)toast('進度已儲存')}}
function logout(){save();location.reload()}
function unlocked(){return ROLES.filter(r=>S.level>=r.unlock)}
function stats(){const members=unlocked();let attack=12+S.level*4,maxHp=135+S.level*30,crit=.06;members.forEach((r,i)=>{attack+=(8+S.level*2)*(i===1?1.22:i===2?1.1:i===3?.75:i===4?.55:1);if(r.id==='tank')maxHp+=120+S.level*15;if(r.id==='doctor')maxHp+=45+S.level*5});Object.values(S.equipment).forEach(it=>{if(!it)return;const m=1+S.enhancement*.12;attack+=it.power*m;maxHp+=it.power*4.2*m;crit+=it.rarity*.009});return{attack:Math.floor(attack),maxHp:Math.floor(maxHp),crit:Math.min(.55,crit)}}
function makeEnemy(){const g=gstage(),boss=S.stage===10,count=unlocked().length,maxHp=Math.floor((65+g*25)*Math.pow(1.092,g-1)*(1+(count-1)*.6)*(boss?4.8:1)),names=MAPS[S.mapIndex].mobs;return{name:(boss?'BOSS · ':'')+names[(S.stage-1)%3],color:(S.stage-1)%3,maxHp,hp:maxHp,attack:Math.floor((6+g*2.2)*(1+(count-1)*.18))*(boss?2:1),boss}}
function spawn(heal=false){E=makeEnemy();const st=stats();if(heal||!Number.isFinite(S.partyHp)||S.partyHp<=0||S.partyHp>st.maxHp)S.partyHp=st.maxHp;hud()}
function gainXp(n){const before=unlocked().length;S.xp+=n;while(S.xp>=S.xpToNext){S.xp-=S.xpToNext;S.level++;S.xpToNext=Math.floor(S.xpToNext*1.28+35);S.partyHp=stats().maxHp;toast('LEVEL UP！Lv.'+S.level);log('角色升至 Lv.'+S.level)}const after=unlocked().length;if(after>before){const role=ROLES[after-1];toast(`解鎖新隊員：${role.name}`);log(`隊伍加入${role.name}，技能「${role.skill}」已解鎖。`);flash('magic');burst(150,160,'#ffe66d',30)}}
function makeItem(force=null){const keys=Object.keys(TYPE),type=keys[Math.floor(Math.random()*keys.length)];let rarity=force;if(rarity===null){const z=Math.random();rarity=z<.004?5:z<.022?4:z<.085?3:z<.23?2:z<.55?1:0}return{id:Date.now().toString(36)+Math.random().toString(36).slice(2),type,rarity,power:Math.floor((7+gstage()*2.4)*RM[rarity]*(.86+Math.random()*.28)),level:gstage()}}
function kill(){const st=stats(),gold=Math.floor((18+gstage()*7)*(E.boss?7:1)),xp=Math.floor((15+gstage()*5)*(E.boss?5:1));S.gold+=gold;gainXp(xp);S.totalKills++;S.dailyKills++;S.killsInStage++;if(Math.random()<(E.boss?.92:.36)){const it=makeItem(E.boss?clamp(Math.floor((gstage()+6)/9),1,5):null);S.inventory.unshift(it);if(S.inventory.length>60)S.inventory.pop();toast(RN[it.rarity]+'裝備掉落！')}floating('+'+fmt(gold)+' 🪙',72,48,'crit');log(`擊敗 ${E.name}，獲得 ${gold} 金幣及 ${xp} XP。`);const need=E.boss?1:6;if(S.killsInStage>=need){S.killsInStage=0;if(S.stage<10)S.stage++;else{S.stage=1;S.mapIndex=(S.mapIndex+1)%MAPS.length;toast('前往 '+MAPS[S.mapIndex].name)}}spawn(false);render();save()}
function damage(amount,label='',style='slash'){if(!E||E.hp<=0)return;const st=stats(),crit=Math.random()<st.crit,d=Math.max(1,Math.floor(amount*(.9+Math.random()*.2)*(crit?1.8:1)));E.hp=Math.max(0,E.hp-d);floating((crit?'CRIT! ':'')+d,72,40,crit?'crit':'');if(label)log(label+'造成 '+d+' 傷害。');flash(style);if(E.hp===0)setTimeout(kill,230);hud()}
function basicAttack(role){const base=stats().attack/unlocked().length;let mult=role.id==='mage'?1.12:role.id==='gunner'?.82:role.id==='tank'?.72:role.id==='doctor'?.55:1;damage(base*mult,'',role.id==='mage'?'magic':role.id==='gunner'?'gun':'slash');shots.push({x:role.id==='gunner'?165:140,y:role.id==='mage'?120:160,tx:330,ty:155,life:14,max:14,color:role.color,type:role.id})}
function useRole(role){if(S.level<role.unlock||Date.now()<ready[role.id]||S.partyHp<=0)return;ready[role.id]=Date.now()+role.cd*1000;const lv=S.skillLevels[role.id]||1,base=stats().attack/unlocked().length;if(role.id==='doctor'){const heal=Math.floor(stats().maxHp*(role.mult+lv*.035));S.partyHp=Math.min(stats().maxHp,S.partyHp+heal);floating('+'+heal,27,38,'heal');flash('heal');burst(130,160,'#7cff98',24);log('群體治療回復 '+heal+' 生命。')}else if(role.id==='tank'){shieldUntil=Date.now()+5000;damage(base*(role.mult+lv*.08),role.skill,'shield');log('守護壁壘啟動：5 秒內大幅減傷。')}else if(role.id==='gunner'){for(let i=0;i<3;i++)setTimeout(()=>{if(E&&E.hp>0)damage(base*(role.mult+lv*.07),i===0?role.skill:'','gun')},i*160)}else{damage(base*(role.mult+lv*.12),role.skill,role.id==='mage'?'magic':'slash')}renderSkills()}
function enemyAttack(){if(!E||E.hp<=0||Date.now()<respawnAt)return;let d=Math.max(1,Math.floor(E.attack*(.82+Math.random()*.32)));if(Date.now()<shieldUntil)d=Math.max(1,Math.floor(d*.35));S.partyHp=Math.max(0,S.partyHp-d);floating('-'+d,25,41,'');shots.push({x:330,y:155,tx:125,ty:160,life:18,max:18,color:'#ff7aa0',type:'enemy'});if(S.partyHp===0){respawnAt=Date.now()+2200;const lost=Math.floor(S.gold*.02);S.gold-=lost;log('隊伍倒下，損失 '+lost+' 金幣。');setTimeout(()=>{if(S){S.partyHp=stats().maxHp;hud()}},2200)}hud()}
function render(){if(!S||!E)return;const st=stats();$('#playerName').textContent=S.account;$('#levelText').textContent=S.level;$('#powerText').textContent=fmt(st.attack+st.maxHp/10);$('#goldText').textContent=fmt(S.gold);$('#gemText').textContent=fmt(S.gems);$('#mapTitle').textContent=MAPS[S.mapIndex].name;$('#stageText').textContent=`Stage ${S.stage} / 10`;$('#attackStat').textContent=fmt(st.attack);$('#hpStat').textContent=fmt(st.maxHp);$('#critStat').textContent=Math.round(st.crit*100)+'%';$('#enhanceStat').textContent='+'+S.enhancement;$('#questBar').style.width=Math.min(100,S.dailyKills/30*100)+'%';$('#questText').textContent=Math.min(30,S.dailyKills)+' / 30';renderNodes();renderTeam();renderGear();renderBag();renderSkills();hud()}
function renderNodes(){const box=$('#stageNodes');box.innerHTML='';for(let i=1;i<=10;i++){const n=document.createElement('span');n.className='stage-node '+(i<S.stage?'done':i===S.stage?'current':'');n.textContent=i;box.appendChild(n)}}
function renderTeam(){const box=$('#teamGrid');box.innerHTML='';const count=unlocked().length;$('#teamCount').textContent=count+' / 5';ROLES.forEach(r=>{const open=S.level>=r.unlock,c=document.createElement('article');c.className=`team-card role-${r.id} ${open?'':'locked'}`;c.innerHTML=`<div class="team-avatar role-${r.id}">${r.icon}</div><div><strong>${r.name}</strong><p>${r.skill}：${r.desc}</p>${open?'<span class="unlock-badge">已加入隊伍</span>':`<span class="unlock-badge">Lv.${r.unlock} 解鎖</span>`}</div><div class="team-level">技能<br>Lv.${S.skillLevels[r.id]||1}</div>`;box.appendChild(c)});renderSkillBar()}
function renderSkillBar(){const bar=$('#classSkillBar');bar.innerHTML='';ROLES.forEach(r=>{const open=S.level>=r.unlock,b=document.createElement('button');b.className=`class-skill role-${r.id} ${open?'':'locked'}`;b.disabled=!open;b.innerHTML=`<span>${r.icon}</span><small>${open?r.skill:'Lv.'+r.unlock}</small><b class="cooldown hidden"></b>`;b.onclick=()=>useRole(r);b.dataset.role=r.id;bar.appendChild(b)});const a=document.createElement('button');a.id='autoButton';a.className='auto-button '+(S.auto?'on':'');a.textContent=S.auto?'AUTO ON':'AUTO OFF';a.onclick=()=>{S.auto=!S.auto;renderSkillBar();save()};bar.appendChild(a);updateCooldowns()}
function renderGear(){const box=$('#equipmentGrid');box.innerHTML='';Object.entries(TYPE).forEach(([k,v])=>{const it=S.equipment[k],d=document.createElement('div');d.className='equipment-slot '+(it?'rarity-'+it.rarity:'');d.innerHTML=`<span class="item-icon">${v[1]}</span><span class="item-name">${it?RN[it.rarity]+v[0]+'<br>⚔ '+it.power:v[0]}</span>`;box.appendChild(d)})}
function renderBag(){const box=$('#inventoryGrid');box.innerHTML='';$('#bagCount').textContent=S.inventory.length+' / 60';if(!S.inventory.length){box.innerHTML='<p class="help-text">擊敗怪物後，裝備會出現在這裡。</p>';return}S.inventory.forEach(it=>{const b=document.createElement('button'),v=TYPE[it.type];b.className='inventory-item rarity-'+it.rarity;b.innerHTML=`<span class="item-icon">${v[1]}</span><span class="item-name">${RN[it.rarity]}${v[0]}<br>⚔ ${it.power}</span>`;b.onclick=()=>equip(it.id);box.appendChild(b)})}
function renderSkills(){const box=$('#skillsList');box.innerHTML='';ROLES.forEach(r=>{const lv=S.skillLevels[r.id]||1,cost=Math.floor(150*Math.pow(1.5,lv-1)*(1+r.unlock/10)),open=S.level>=r.unlock,c=document.createElement('article');c.className='skill-card';c.innerHTML=`<span>${r.icon}</span><div><strong>${r.name} · ${r.skill} Lv.${lv}</strong><p>${open?r.desc:'Lv.'+r.unlock+' 後解鎖'}</p></div>`;const b=document.createElement('button');b.className='pixel-button gold';b.textContent=fmt(cost);b.disabled=!open||S.gold<cost;b.onclick=()=>{if(S.gold<cost)return toast('金幣不足');S.gold-=cost;S.skillLevels[r.id]=lv+1;render();save()};c.appendChild(b);box.appendChild(c)});updateCooldowns()}
function hud(){if(!S||!E)return;const st=stats();$('#heroHpText').textContent=`${Math.max(0,Math.floor(S.partyHp))} / ${st.maxHp}`;$('#heroHpBar').style.width=clamp(S.partyHp/st.maxHp*100,0,100)+'%';$('#enemyName').textContent=E.name;$('#enemyHpText').textContent=`${Math.max(0,Math.floor(E.hp))} / ${E.maxHp}`;$('#enemyHpBar').style.width=clamp(E.hp/E.maxHp*100,0,100)+'%';$('#goldText').textContent=fmt(S.gold)}
function updateCooldowns(){$$('.class-skill').forEach(b=>{const c=b.querySelector('.cooldown'),n=Math.max(0,(ready[b.dataset.role]||0)-Date.now());if(c){c.classList.toggle('hidden',n<=0);c.textContent=n>0?(n/1000).toFixed(1):''}})}
function equip(id){const i=S.inventory.findIndex(x=>x.id===id);if(i<0)return;const it=S.inventory[i],old=S.equipment[it.type];S.equipment[it.type]=it;S.inventory.splice(i,1);if(old)S.inventory.unshift(old);S.partyHp=Math.min(S.partyHp,stats().maxHp);render();save();toast('已裝備 '+RN[it.rarity]+TYPE[it.type][0])}
function enhance(){const cost=500*Math.pow(2,S.enhancement);if(S.gold<cost)return toast('需要 '+fmt(cost)+' 金幣');S.gold-=cost;S.enhancement++;render();save();toast('全身裝備強化 +'+S.enhancement)}
function unequip(){Object.keys(S.equipment).forEach(k=>{if(S.equipment[k])S.inventory.unshift(S.equipment[k]);S.equipment[k]=null});S.inventory=S.inventory.slice(0,60);render();save()}
function synth(){const g={};S.inventory.forEach(i=>(g[i.rarity]??=[]).push(i));const r=Object.keys(g).map(Number).filter(x=>x<5&&g[x].length>=5).sort((a,b)=>a-b)[0];if(r===undefined)return toast('未有 5 件相同稀有度裝備');const ids=new Set(g[r].slice(-5).map(i=>i.id));S.inventory=S.inventory.filter(i=>!ids.has(i.id));S.inventory.unshift(makeItem(r+1));render();save();toast('合成成功')}
function sell(){const a=S.inventory.filter(i=>i.rarity===0);if(!a.length)return toast('沒有普通裝備');const v=a.reduce((n,i)=>n+i.power*5,0);S.inventory=S.inventory.filter(i=>i.rarity!==0);S.gold+=v;render();save();toast('獲得 '+fmt(v)+' 金幣')}
function switchTab(name){$$('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));['team','equipment','inventory','skills'].forEach(n=>$('#'+n+'Pane').classList.toggle('hidden',n!==name))}
function log(t){const d=document.createElement('div');d.textContent='['+new Date().toLocaleTimeString()+'] '+t;$('#logLines').appendChild(d);while($('#logLines').children.length>40)$('#logLines').firstChild.remove();$('.battle-log').scrollTop=$('.battle-log').scrollHeight}
function toast(t){const d=document.createElement('div');d.className='toast';d.textContent=t;document.body.appendChild(d);setTimeout(()=>d.remove(),2200)}
function floating(t,l,top,cls=''){const d=document.createElement('span');d.className='float-text '+cls;d.style.left=l+'%';d.style.top=top+'%';d.textContent=t;$('#floatingLayer').appendChild(d);setTimeout(()=>d.remove(),950)}
function flash(kind){const d=document.createElement('div');d.className='skill-flash '+kind;$('.battle-area').appendChild(d);setTimeout(()=>d.remove(),500)}
function burst(x,y,color,count){for(let i=0;i<count;i++){const a=Math.random()*Math.PI*2,s=.4+Math.random()*2;sparks.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:12+Math.random()*18,color})}}
function resize(){cv.width=420;cv.height=250;ctx.imageSmoothingEnabled=false}
function rr(x,y,w,h,r){ctx.beginPath();ctx.moveTo(x+r,y);ctx.lineTo(x+w-r,y);ctx.quadraticCurveTo(x+w,y,x+w,y+r);ctx.lineTo(x+w,y+h-r);ctx.quadraticCurveTo(x+w,y+h,x+w-r,y+h);ctx.lineTo(x+r,y+h);ctx.quadraticCurveTo(x,y+h,x,y+h-r);ctx.lineTo(x,y+r);ctx.quadraticCurveTo(x,y,x+r,y);ctx.closePath()}
function slime(x,y,size,color,role,bounce=0,boss=false){ctx.save();ctx.translate(Math.round(x),Math.round(y));ctx.scale(1+bounce*.04,1-bounce*.04);const w=size*1.18,h=size*.86;ctx.fillStyle='#fff';rr(-w/2-4,-h-4,w+8,h+8,11);ctx.fill();ctx.fillStyle='#100d1d';rr(-w/2-1,-h-1,w+2,h+2,9);ctx.fill();ctx.fillStyle=color;rr(-w/2+3,-h+3,w-6,h-5,8);ctx.fill();ctx.fillStyle='#ffffff44';ctx.fillRect(-w/2+8,-h+8,w*.24,4);ctx.fillStyle='#171321';ctx.fillRect(-w*.18,-h*.48,4,6);ctx.fillRect(w*.15,-h*.48,4,6);ctx.fillRect(-3,-h*.27,7,3);accessory(role,w,h,boss);ctx.restore()}
function accessory(role,w,h,boss){ctx.fillStyle='#171321';if(boss){ctx.fillRect(-14,-h-14,28,14);ctx.fillStyle='#ffd650';ctx.fillRect(-11,-h-11,22,9);ctx.fillRect(-11,-h-16,5,6);ctx.fillRect(-2,-h-19,5,9);ctx.fillRect(7,-h-16,5,6);return}if(role==='swordsman'){ctx.fillRect(w/2-2,-h+2,4,34);ctx.fillStyle='#f8f6ff';ctx.fillRect(w/2-1,-h,2,25);ctx.fillStyle='#ffd650';ctx.fillRect(w/2-6,-h+24,12,3)}else if(role==='mage'){ctx.fillStyle='#3a275e';ctx.fillRect(-w*.34,-h-10,w*.68,10);ctx.fillRect(-w*.22,-h-19,w*.44,12);ctx.fillStyle='#d882ff';ctx.fillRect(10,-h-17,5,5)}else if(role==='gunner'){ctx.fillStyle='#22283d';ctx.fillRect(w/2-2,-h+20,20,6);ctx.fillStyle='#7bd8ff';ctx.fillRect(w/2+14,-h+21,6,4)}else if(role==='tank'){ctx.fillStyle='#dbe8ff';ctx.fillRect(w/2-1,-h+12,14,24);ctx.fillStyle='#6f90bd';ctx.fillRect(w/2+2,-h+15,8,18)}else if(role==='doctor'){ctx.fillStyle='#fff';ctx.fillRect(-8,-h-12,16,9);ctx.fillRect(-5,-h-17,10,7);ctx.fillStyle='#e95062';ctx.fillRect(-2,-h-15,4,10);ctx.fillRect(-5,-h-12,10,4)}}
function bg(t){const m=MAPS[S.mapIndex];ctx.fillStyle=m.sky;ctx.fillRect(0,0,420,250);ctx.fillStyle='#d8b4f2';[[12,20,65],[98,34,80],[285,18,80]].forEach(a=>{ctx.fillRect(a[0],a[1],a[2],5);ctx.fillRect(a[0]+18,a[1]-7,a[2]*.45,5)});ctx.fillStyle=m.far;for(let x=0;x<420;x+=20)ctx.fillRect(x,90-(30+(x/20%3)*7),22,60);ctx.fillStyle=m.ground;ctx.fillRect(0,95,420,155);ctx.fillStyle='#302550';for(let x=0;x<420;x+=22)ctx.fillRect(x,205+(x/22%2)*4,14,4);ctx.fillStyle='#8065b1';ctx.beginPath();ctx.ellipse(215,190,145,38,0,0,7);ctx.fill();ctx.fillStyle='#c8a7ff';ctx.fillRect(205+(Math.floor(t/300)%4)*2,150,4,4)}
function drawShots(){shots.forEach(s=>{const p=1-s.life/s.max,x=s.x+(s.tx-s.x)*p,y=s.y+(s.ty-s.y)*p;ctx.fillStyle='#fff';ctx.fillRect(x-4,y-4,8,8);ctx.fillStyle=s.color;ctx.fillRect(x-2,y-2,4,4);s.life--});for(let i=shots.length-1;i>=0;i--)if(shots[i].life<=0)shots.splice(i,1)}
function drawSparks(){sparks.forEach(s=>{ctx.fillStyle=s.color;ctx.fillRect(s.x,s.y,3,3);s.x+=s.vx;s.y+=s.vy;s.vy+=.03;s.life--});for(let i=sparks.length-1;i>=0;i--)if(sparks[i].life<=0)sparks.splice(i,1)}
function draw(t){if(!S||!E)return;bg(t);const pos=[[92,175],[145,145],[75,220],[150,215],[205,180]],members=unlocked(),b=Math.sin(t/170);members.forEach((r,i)=>slime(pos[i][0],pos[i][1]+b*(i%2?2:-2),i===0?43:36,r.color,r.id,Math.max(0,(i%2?b:-b)),false));const colors=['#65e35d','#4cb8ff','#ff6b67'];slime(335,185-b*3,E.boss?72:58,colors[E.color],E.color===1?'mage':E.color===2?'tank':'',Math.max(0,b),E.boss);drawShots();drawSparks()}
function combat(t){if(!S||!E||!S.auto||S.partyHp<=0||Date.now()<respawnAt)return;const members=unlocked();members.forEach(r=>{if(t-(lastAttack[r.id]||0)>r.interval){lastAttack[r.id]=t;basicAttack(r)}});if(t-lastEnemy>1500){lastEnemy=t;enemyAttack()}members.forEach(r=>{const healOk=r.id!=='doctor'||S.partyHp<stats().maxHp*.62;if(Date.now()>=(ready[r.id]||0)&&healOk)useRole(r)})}
function loop(t){requestAnimationFrame(loop);if(!S)return;combat(t);if(t-frameAt<33)return;frameAt=t;draw(t);updateCooldowns()}
function bind(){$('#loginButton').onclick=login;$('#registerButton').onclick=register;$('#passwordInput').addEventListener('keydown',e=>{if(e.key==='Enter')login()});$('#manualSaveButton').onclick=()=>save(true);$('#logoutButton').onclick=logout;$('#enhanceButton').onclick=enhance;$('#unequipButton').onclick=unequip;$('#synthButton').onclick=synth;$('#sellButton').onclick=sell;$('#claimOfflineButton').onclick=()=>{if(pending){S.gold+=pending.gold;gainXp(pending.xp);pending=null;render();save()}$('#offlineModal').classList.add('hidden')};$$('.tab').forEach(b=>b.onclick=()=>switchTab(b.dataset.tab));$$('.menu-button[data-focus-tab]').forEach(b=>b.onclick=()=>{switchTab(b.dataset.focusTab);if(innerWidth<760)$('.right-panel').scrollIntoView({behavior:'smooth'})});addEventListener('resize',resize);addEventListener('beforeunload',()=>save())}
function init(){if(!cv||!ctx){document.body.textContent='瀏覽器不支援 Canvas';return}bind();const last=get(LAST);if(last)$('#accountInput').value=last;resize();setInterval(()=>save(),5000);requestAnimationFrame(loop)}
init();
})();